### PR TITLE
Updated mods to the latest but kept customizations

### PR DESCRIPTION
**Pull request by An0n3m0us**
Updated all of the mods to the latest versions (except `streets`).

I'll either do streets as a second commit or leave it as is depending on what is best to do.

### CODE REVIEW

**Comment by An0n3m0us** [comment]
Oops I forgot to test it xD
I'll do that now.

**Comment by davisonio** [comment]
Woah thanks for doing this. It's gonna take me a while to review but I'll try get round to it soon.

**Comment by An0n3m0us** [comment]
You're welcome! Sure, that's fine; there's no rush. I'm planning to make a script soon so that one wouldn't have to do it manually.

**Comment by An0n3m0us** [comment]
Oh no; I only took in consideration the customized mods mentioned in the README : |
It seems like loads more mods were customized in PRs.

If you give me a list of the PRs you want to be kept, I'll merge them into the correct locations.

**Comment by davisonio** [comment]
Hey thanks for this, I've just merged your changes made here with mine and all the mods should be updated now! Feel free to submit a PR if I missed an update.

**Pull request closed without merging**
